# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c35e8d7f8c7ea1462abc14b51d4396068e843a0ff10c3a89d621529a969d096904021d42c483727a1921e5a2220ffded2b7ee93e8feb4998c4ede16e305ada3

test:
  secret_key_base: f992ee3e051007b46d9d7008b8289e7c78d55e37dd17f43b8b57ccf8c621c44844624db7167e2f425f01c04d560763de8748017d189d6d815c6b44dd7c8cf2c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
